name: Nx Java CI

env:
  NX_BATCH_MODE: true

on:
  push:

jobs:
  initial-build:
    runs-on: ubuntu-latest
    env:
      NX_CI_EXECUTION_ENV: 'initial-build'
    steps:
      - name: Set up JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Checkout maven
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          filter: tree:0
          fetch-depth: 0
          persist-credentials: false

      - name: Download Maven distribution
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: maven-distributions
          path: maven-dist

      - name: List downloaded files
        shell: bash
        run: ls -la maven-dist

      - name: Extract Maven distribution
        shell: bash
        run: |
          mkdir -p maven-local
          if [ "${{ runner.os }}" = "Windows" ]; then
            unzip maven-dist/apache-maven-*-bin.zip -d maven-local
            # Get the name of the extracted directory
            MAVEN_DIR=$(ls maven-local)
            # Move contents up one level
            mv "maven-local/$MAVEN_DIR"/* maven-local/
            rm -r "maven-local/$MAVEN_DIR"
          else
            tar xzf maven-dist/apache-maven-*-bin.tar.gz -C maven-local --strip-components 1
          fi
          echo "MAVEN_HOME=$PWD/maven-local" >> $GITHUB_ENV
          echo "$PWD/maven-local/bin" >> $GITHUB_PATH

      - name: Start CI run
        run: ./nx start-ci-run --distribute-on="5 linux-large" --stop-agents-after="verify-ci"

      - name: Print SHA
        run: echo "${{ github.sha }}"

      - name: Set up Maven
        shell: bash
        run: ./mvnw --errors --batch-mode --show-version org.apache.maven.plugins:maven-wrapper-plugin:3.3.2:wrapper "-Dmaven=4.0.0-rc-3"

      - name: Build Maven distributions
        shell: bash
        run: ./nx run-many -t verify-ci --verbose

